version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: resumate
      POSTGRES_USER: resumate_user
      POSTGRES_PASSWORD: resumate_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - resumate_network

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/resumate
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - resumate_network

  frontend:
    image: node:14
    working_dir: /resumate/frontend
    volumes:
      - ./frontend:/resumate/frontend
    command: >
      bash -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
    networks:
      - resumate_network


networks:
  resumate_network:
    driver: bridge

volumes:
  postgres_data: